### PR TITLE
Improved path handling in run script

### PR DESCRIPTION
**Pull request by mrghg**
Aiming to make it easier to start from a clean repository. A lot of the error checking for paths is suppressed. The output_path functionality is improved, and public/private is now passed to Paths.

This is still a work in progress. The run scripts need to be edited to make use of this new functionality

### CODE REVIEW

**Comment by qq23840** [comment]
Looks good to me - just added a line to setup the flask path in `setup.py`

**Comment by lukewestern** [comment]
I'm getting 3 test failures:

============================================ short test summary info =============================================
FAILED tests/test_config.py::test_paths - KeyError: 'output_path_private'
FAILED tests/test_config.py::test_output_path - KeyError: 'output_path_private'
FAILED tests/test_io.py::test_read_gcwerks_flask - AttributeError: 'Paths' object has no attribute 'gcms_flask_path'
============================= 3 failed, 17 passed, 95 warnings in 180.66s (0:03:00) ==============================

**Comment by qq23840** [comment]
I'm not getting these, I think because I've changed my config file and made appropriate directories while testing. Probably worth checking that the config.py sets up the default config file in such a way that these errors don't occur?

**Comment by lukewestern** [comment]
Good point. I forgot to update the config paths. Tests are passing now

**Pull request merged**
